# Generated by Django 5.2.12 on 2026-03-17 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('species', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('reptile', 'Рептилия'), ('other', 'Другое')], max_length=20, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(360)], verbose_name='Возраст (мес.)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(200)], verbose_name='Вес (кг)')),
                ('health_notes', models.TextField(blank=True, verbose_name='Особенности здоровья')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-created_at'],
            },
        ),
    ]
