# Generated by Django 5.2.12 on 2026-06-10 23:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('200'))], verbose_name='Вес (кг)'),
        ),
    ]
