# Generated by Django 5.2.12 on 2026-03-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (руб.)')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Длительность (мин.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctors.specialty', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['specialty', 'name'],
            },
        ),
    ]
