# Generated by Django 5.2.12 on 2026-06-10 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0004_alter_schedule_slot_duration'),
        ('pets', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'date', 'time_slot'), name='uniq_active_slot_per_doctor'),
        ),
    ]
