# Generated by Django 5.2.12 on 2026-09-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-updated_at',), 'verbose_name': 'позиция корзины', 'verbose_name_plural': 'позиции корзины'},
        ),
    ]
