# Generated by Django 5.2.12 on 2026-06-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='КубКубыч', max_length=120, verbose_name='Название магазина')),
                ('contact_email', models.EmailField(default='hello@kubkubych.ru', max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(default='+7 (495) 123-45-67', max_length=30, verbose_name='Контактный телефон')),
                ('address', models.CharField(default='Москва, доставка по России', max_length=255, verbose_name='Адрес')),
                ('about_text', models.TextField(blank=True, verbose_name='О магазине')),
                ('mission_text', models.TextField(blank=True, verbose_name='Миссия')),
                ('delivery_text', models.TextField(blank=True, verbose_name='Доставка и оплата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки магазина',
                'verbose_name_plural': 'настройки магазина',
            },
        ),
    ]
