# Generated by Django 5.2.12 on 2026-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(blank=True, default='', verbose_name='Фото (ссылка)'),
        ),
    ]
