# Generated by Django 5.2.12 on 2026-06-10 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность слота (мин.)'),
        ),
    ]
