# Generated by Django 5.2.12 on 2026-06-22 20:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'серия', 'verbose_name_plural': 'серии'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'набор', 'verbose_name_plural': 'наборы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='age_max',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст до'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_min',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст от'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)], verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество деталей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Цена'),
        ),
    ]
