# Generated by Django 5.2.12 on 2026-09-16 10:41

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorited_by_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', through='products.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Добавили в избранное'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_file',
            field=models.FileField(blank=True, upload_to='product-specifications/', verbose_name='Спецификация'),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, verbose_name='Slug')),
                ('article', models.CharField(db_index=True, max_length=40, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_from', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст от')),
                ('age_to', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст до')),
                ('pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество деталей')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Цена')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)], verbose_name='Скидка, %')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение')),
                ('specification_file', models.TextField(blank=True, max_length=100, verbose_name='Спецификация')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в каталоге')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.category', verbose_name='Серия')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical набор',
                'verbose_name_plural': 'historical наборы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
